import assert from 'node:assert/strict';
import test from 'node:test';
import { diffContent, formatCommitMessage } from './content_diff.mjs';

const base = () => ({
  concepts: [{ concept_id: 'c1', level_auto: 'A1' }],
  lexemes: [{ lexeme_id: 'lex-de-laufen', concept_id: 'c1', lang: 'de', text: 'laufen', is_primary: true }],
  concept_definitions: [{ concept_id: 'c1', lang: 'de', short_definition: 'sich bewegen', synonyms_json: ['rennen'], antonyms_json: [] }],
  examples: [{ example_id: 'e1', concept_id: 'c1', lang: 'de' }],
  clusters: [],
  cluster_members: []
});

test('new concept → new word with level + German surface form', () => {
  const old = base();
  const nw = base();
  nw.concepts.push({ concept_id: 'c2', level_override: 'B1' });
  nw.lexemes.push(
    { lexeme_id: 'lex-en-contract', concept_id: 'c2', lang: 'en', text: 'contract' },
    { lexeme_id: 'lex-de-vertrag', concept_id: 'c2', lang: 'de', text: 'der Vertrag', is_primary: true }
  );
  const d = diffContent(old, nw);
  assert.equal(d.newConcepts, 1);
  assert.deepEqual(d.newWords, [{ word: 'der Vertrag', level: 'B1' }]); // de primary preferred over en
  assert.deepEqual(d.perLevel, { B1: 1 });
});

test('empty/missing old → everything counts as new', () => {
  const d = diffContent(null, base());
  assert.equal(d.newConcepts, 1);
  assert.equal(d.newWords[0].word, 'laufen');
});

test('enrichment: synonyms, antonyms, examples, filled definitions', () => {
  const old = base();
  const nw = base();
  nw.concept_definitions[0].synonyms_json = ['rennen', 'eilen']; // +1 syn
  nw.concept_definitions[0].antonyms_json = ['stehen']; // +1 ant
  nw.concept_definitions.push({ concept_id: 'c1', lang: 'it', short_definition: 'correre', synonyms_json: [], antonyms_json: [] }); // newly filled def
  nw.examples.push({ example_id: 'e2', concept_id: 'c1', lang: 'en' }); // +1 ex
  const d = diffContent(old, nw);
  assert.equal(d.synDelta, 1);
  assert.equal(d.antDelta, 1);
  assert.equal(d.newExamples, 1);
  assert.deepEqual(d.exByLang, { en: 1 });
  assert.equal(d.defsFilled, 1);
});

test('no model/AI name ever appears in a commit message', () => {
  const old = base();
  const nw = base();
  // Even if a record somehow carries a model name, the message must not echo it.
  nw.concepts.push({ concept_id: 'c2', level_auto: 'A2' });
  nw.lexemes.push({ lexeme_id: 'lex-de-haus', concept_id: 'c2', lang: 'de', text: 'das Haus', is_primary: true });
  nw.concept_definitions.push({ concept_id: 'c2', lang: 'de', short_definition: 'a building', synonyms_json: [], antonyms_json: [], generated_by: 'modela:14b' });
  nw.examples.push({ example_id: 'e2', concept_id: 'c2', lang: 'de', generated_by: 'modelb:8b' });
  const { subject, body } = formatCommitMessage(diffContent(old, nw), { tag: 't' });
  const text = `${subject}\n${body}`.toLowerCase();
  // The stripper is generic (it never echoes generated_by), so fake model names
  // exercise it just like real ones - and keep real vendor names out of the repo.
  for (const name of ['modela', 'modelb', 'generated by']) {
    assert.ok(!text.includes(name), `commit message leaked "${name}"`);
  }
});

test('a blank short_definition does not count as filled', () => {
  const old = base();
  old.concept_definitions[0].short_definition = '   ';
  const nw = base();
  nw.concept_definitions[0].short_definition = 'sich bewegen';
  assert.equal(diffContent(old, nw).defsFilled, 1);
});

test('no content change → chore subject, not a words claim', () => {
  const { subject } = formatCommitMessage(diffContent(base(), base()));
  assert.equal(subject, 'chore(content): rebuild runtime packs');
});

test('subject is compact and lists levels; body names the words', () => {
  const old = base();
  const nw = base();
  nw.concepts.push({ concept_id: 'c2', level_auto: 'A2' });
  nw.lexemes.push({ lexeme_id: 'lex-de-haus', concept_id: 'c2', lang: 'de', text: 'das Haus', is_primary: true });
  const { subject, body } = formatCommitMessage(diffContent(old, nw), { tag: 'unit-test' });
  assert.match(subject, /^content: \+1 word \(A2\)$/);
  assert.match(body, /New words \(1\): das Haus/);
  assert.match(body, /Autopilot batch - unit-test/);
});
