import assert from 'node:assert/strict';
import test from 'node:test';

import { buildGenerateBrief } from './generate_brief.mjs';

function buildFixture() {
  return {
    manifest: {
      pack_id: 'lexicon.source',
      version: 'test',
      languages_present: ['de', 'en', 'it'],
    },
    content: {
      concepts: [
        {
          concept_id: 'concept-hour',
          pos: 'noun',
          level_auto: 'A1',
          level_override: null,
          domain_tags: ['Time'],
        },
        {
          concept_id: 'concept-now',
          pos: 'adv',
          level_auto: 'A1',
          level_override: null,
          domain_tags: ['Time'],
        },
        {
          concept_id: 'concept-time-of-day',
          pos: 'noun',
          level_auto: 'A1',
          level_override: null,
          domain_tags: ['Time'],
        },
        {
          concept_id: 'concept-great',
          pos: 'adj',
          level_auto: 'A2',
          level_override: null,
          domain_tags: ['Daily'],
        },
      ],
      lexemes: [
        {
          lexeme_id: 'lex-hour-de',
          concept_id: 'concept-hour',
          lang: 'de',
          text: 'Stunde',
          lemma: 'Stunde',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-hour-en',
          concept_id: 'concept-hour',
          lang: 'en',
          text: 'the hour',
          lemma: 'hour',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-hour-it',
          concept_id: 'concept-hour',
          lang: 'it',
          text: "l'ora",
          lemma: 'ora',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-now-de',
          concept_id: 'concept-now',
          lang: 'de',
          text: 'jetzt',
          lemma: 'jetzt',
          pos: 'adv',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-now-en',
          concept_id: 'concept-now',
          lang: 'en',
          text: 'now',
          lemma: 'now',
          pos: 'adv',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-now-it',
          concept_id: 'concept-now',
          lang: 'it',
          text: 'ora',
          lemma: 'ora',
          pos: 'adv',
          is_primary: false,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-time-de',
          concept_id: 'concept-time-of-day',
          lang: 'de',
          text: 'Uhrzeit',
          lemma: 'Uhrzeit',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-time-en',
          concept_id: 'concept-time-of-day',
          lang: 'en',
          text: 'the time',
          lemma: 'time',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-time-it',
          concept_id: 'concept-time-of-day',
          lang: 'it',
          text: "l'ora",
          lemma: 'ora',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-great-de',
          concept_id: 'concept-great',
          lang: 'de',
          text: 'großartig',
          lemma: 'großartig',
          pos: 'adj',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-great-en',
          concept_id: 'concept-great',
          lang: 'en',
          text: 'great',
          lemma: 'great',
          pos: 'adj',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-great-it',
          concept_id: 'concept-great',
          lang: 'it',
          text: 'fantastico',
          lemma: 'fantastico',
          pos: 'adj',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
      ],
      concept_definitions: [
        {
          concept_id: 'concept-hour',
          lang: 'de',
          short_definition: 'Zeitdauer von sechzig Minuten.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-hour',
          lang: 'en',
          short_definition: 'A period of sixty minutes.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-hour',
          lang: 'it',
          short_definition: 'Un periodo di sessanta minuti.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-now',
          lang: 'de',
          short_definition: 'In diesem Moment.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-now',
          lang: 'en',
          short_definition: 'At this moment.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-now',
          lang: 'it',
          short_definition: 'In questo momento.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-time-of-day',
          lang: 'de',
          short_definition: 'Zeit des Tages.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-time-of-day',
          lang: 'en',
          short_definition: 'Time of day.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-time-of-day',
          lang: 'it',
          short_definition: 'Ora del giorno.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-great',
          lang: 'de',
          short_definition: 'Sehr gut.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: ['schrecklich'],
          antonym_policy_json: null,
          hint_text: null,
        },
        {
          concept_id: 'concept-great',
          lang: 'en',
          short_definition: 'Very good.',
          usage_note: null,
          synonyms_json: ['awesome'],
          antonyms_json: ['terrible'],
          antonym_policy_json: null,
          hint_text: null,
        },
        {
          concept_id: 'concept-great',
          lang: 'it',
          short_definition: 'Molto buono.',
          usage_note: null,
          synonyms_json: ['ottimo'],
          antonyms_json: ['terribile'],
          antonym_policy_json: null,
          hint_text: null,
        },
      ],
      examples: [
        { example_id: 'ex-hour-de', concept_id: 'concept-hour', lang: 'de', sentence: 'Der Kurs dauert sechzig Minuten.' },
        { example_id: 'ex-hour-en', concept_id: 'concept-hour', lang: 'en', sentence: 'The class lasts sixty minutes.' },
        { example_id: 'ex-hour-it', concept_id: 'concept-hour', lang: 'it', sentence: 'Il corso dura sessanta minuti.' },
        { example_id: 'ex-now-de', concept_id: 'concept-now', lang: 'de', sentence: 'Ich kann in diesem Moment nicht sprechen.' },
        { example_id: 'ex-now-en', concept_id: 'concept-now', lang: 'en', sentence: 'I cannot talk at this moment.' },
        { example_id: 'ex-now-it', concept_id: 'concept-now', lang: 'it', sentence: 'Non posso parlare in questo momento.' },
        { example_id: 'ex-time-de', concept_id: 'concept-time-of-day', lang: 'de', sentence: 'Die Anzeige zeigt eine späte Stunde.' },
        { example_id: 'ex-time-en', concept_id: 'concept-time-of-day', lang: 'en', sentence: 'The display shows a late time.' },
        { example_id: 'ex-time-it', concept_id: 'concept-time-of-day', lang: 'it', sentence: 'Il display mostra un orario tardo.' },
        { example_id: 'ex-great-de', concept_id: 'concept-great', lang: 'de', sentence: 'Das Konzert kam beim Publikum sehr gut an.' },
        { example_id: 'ex-great-en', concept_id: 'concept-great', lang: 'en', sentence: 'The concert was a big success with the audience.' },
        { example_id: 'ex-great-it', concept_id: 'concept-great', lang: 'it', sentence: 'Il concerto ha entusiasmato tutto il pubblico.' },
      ],
      lexeme_forms: [
        { form_id: 'form-hour-it', lexeme_id: 'lex-hour-it', lang: 'it', surface: 'ora', form_role: 'core', sort_order: 0 },
        { form_id: 'form-now-it', lexeme_id: 'lex-now-it', lang: 'it', surface: 'ora', form_role: 'core', sort_order: 0 },
        { form_id: 'form-time-it', lexeme_id: 'lex-time-it', lang: 'it', surface: 'ora', form_role: 'core', sort_order: 0 },
        { form_id: 'form-great-de', lexeme_id: 'lex-great-de', lang: 'de', surface: 'großartig', form_role: 'core', sort_order: 0 },
      ],
    },
  };
}

test('buildGenerateBrief produces split-oriented brief for ambiguous ora', () => {
  const fixture = buildFixture();
  const summary = buildGenerateBrief({
    manifest: fixture.manifest,
    content: fixture.content,
    term: 'ora',
    lang: 'it',
  });

  assert.equal(summary.decision_hint, 'split_review_required');
  assert.equal(summary.core_concept_ids.length, 3);
  assert.equal(summary.template.core_concepts.length, 3);
  assert.equal(summary.template.related_words.confusable_neighbors.length, 0);
  assert.ok(
    summary.template.accepted_answers_and_forms.some(
      (row) => row.concept_id === 'concept-now' && row.by_lang.it.accepted_lexemes.includes('ora'),
    ),
  );
});

test('buildGenerateBrief produces existing-concept brief for support-only awesome', () => {
  const fixture = buildFixture();
  const summary = buildGenerateBrief({
    manifest: fixture.manifest,
    content: fixture.content,
    term: 'awesome',
    lang: 'en',
  });

  assert.equal(summary.decision_hint, 'support_hit_review_required');
  assert.deepEqual(summary.core_concept_ids, ['concept-great']);
  assert.equal(summary.template.core_concepts[0].concept_id, 'concept-great');
  assert.equal(summary.template.synonyms_antonyms[0].by_lang.en.synonyms[0], 'awesome');
});

test('buildGenerateBrief keeps nearby family bounded when strong signals exist', () => {
  const fixture = {
    manifest: {
      pack_id: 'lexicon.source',
      version: 'test',
      languages_present: ['de', 'en', 'it'],
    },
    content: {
      concepts: [
        {
          concept_id: 'concept-compare-noun',
          pos: 'noun',
          level_auto: 'A2',
          domain_tags: ['Daily', 'Abstract', 'Education'],
        },
        {
          concept_id: 'concept-compare-verb',
          pos: 'verb',
          level_auto: 'A2',
          domain_tags: ['Daily', 'Abstract', 'Education'],
        },
      ],
      lexemes: [
        {
          lexeme_id: 'lex-compare-noun-de',
          concept_id: 'concept-compare-noun',
          lang: 'de',
          text: 'Vergleich',
          lemma: 'Vergleich',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-compare-noun-en',
          concept_id: 'concept-compare-noun',
          lang: 'en',
          text: 'the comparison',
          lemma: 'comparison',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-compare-noun-it',
          concept_id: 'concept-compare-noun',
          lang: 'it',
          text: 'il confronto',
          lemma: 'confronto',
          pos: 'noun',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-compare-verb-de',
          concept_id: 'concept-compare-verb',
          lang: 'de',
          text: 'vergleichen',
          lemma: 'vergleichen',
          pos: 'verb',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-compare-verb-en',
          concept_id: 'concept-compare-verb',
          lang: 'en',
          text: 'to compare',
          lemma: 'compare',
          pos: 'verb',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
        {
          lexeme_id: 'lex-compare-verb-it',
          concept_id: 'concept-compare-verb',
          lang: 'it',
          text: 'confrontare',
          lemma: 'confrontare',
          pos: 'verb',
          is_primary: true,
          meaning_status: 'exact',
          status: 'approved',
          is_active: true,
        },
      ],
      concept_definitions: [
        {
          concept_id: 'concept-compare-noun',
          lang: 'de',
          short_definition: 'Das Prüfen von Ähnlichkeiten oder Unterschieden.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-compare-noun',
          lang: 'en',
          short_definition: 'Checking similarities or differences.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-compare-noun',
          lang: 'it',
          short_definition: 'Controllo di somiglianze o differenze.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-compare-verb',
          lang: 'de',
          short_definition: 'Zwei Dinge nebeneinander prüfen.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-compare-verb',
          lang: 'en',
          short_definition: 'Check two things side by side.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
        {
          concept_id: 'concept-compare-verb',
          lang: 'it',
          short_definition: 'Mettere a confronto due cose.',
          usage_note: null,
          synonyms_json: [],
          antonyms_json: [],
          antonym_policy_json: 'intentionally_none',
          hint_text: null,
        },
      ],
      examples: [
        { example_id: 'ex-compare-noun-de', concept_id: 'concept-compare-noun', lang: 'de', sentence: 'Mit zwei Angeboten wird die Wahl klarer.' },
        { example_id: 'ex-compare-noun-en', concept_id: 'concept-compare-noun', lang: 'en', sentence: 'Two offers make the choice clearer.' },
        { example_id: 'ex-compare-noun-it', concept_id: 'concept-compare-noun', lang: 'it', sentence: 'Due offerte rendono la scelta più chiara.' },
        { example_id: 'ex-compare-verb-de', concept_id: 'concept-compare-verb', lang: 'de', sentence: 'Sie prüft beide Modelle nebeneinander.' },
        { example_id: 'ex-compare-verb-en', concept_id: 'concept-compare-verb', lang: 'en', sentence: 'She checks both models side by side.' },
        { example_id: 'ex-compare-verb-it', concept_id: 'concept-compare-verb', lang: 'it', sentence: 'Controlla i due modelli uno accanto all’altro.' },
      ],
      lexeme_forms: [
        { form_id: 'form-compare-noun-de', lexeme_id: 'lex-compare-noun-de', lang: 'de', surface: 'der Vergleich', form_role: 'core', sort_order: 0 },
        { form_id: 'form-compare-noun-en', lexeme_id: 'lex-compare-noun-en', lang: 'en', surface: 'the comparison', form_role: 'core', sort_order: 0 },
        { form_id: 'form-compare-noun-it', lexeme_id: 'lex-compare-noun-it', lang: 'it', surface: 'il confronto', form_role: 'core', sort_order: 0 },
        { form_id: 'form-compare-verb-de', lexeme_id: 'lex-compare-verb-de', lang: 'de', surface: 'vergleichen', form_role: 'core', sort_order: 0 },
      ],
      clusters: [
        {
          cluster_id: 'cluster-compare',
          lang: 'de',
          label: 'compare family',
          type: 'semantic',
        },
      ],
      cluster_members: [
        {
          cluster_id: 'cluster-compare',
          lexeme_id: 'lex-compare-noun-de',
          position: 0,
        },
        {
          cluster_id: 'cluster-compare',
          lexeme_id: 'lex-compare-verb-de',
          position: 1,
        },
      ],
    },
  };

  const summary = buildGenerateBrief({
    manifest: fixture.manifest,
    content: fixture.content,
    term: 'Vergleich',
    lang: 'de',
  });

  assert.equal(summary.decision_hint, 'existing_concept_found');
  assert.equal(summary.template.related_words.nearby_family_status, 'auto_bounded');
  assert.equal(summary.template.related_words.nearby_family.length, 1);
  assert.equal(summary.template.related_words.nearby_family[0].concept_id, 'concept-compare-verb');
  assert.ok(
    summary.template.related_words.nearby_family[0].reasons.includes('shared_cluster:compare family'),
  );
});
